# railway.toml - Updated to use npm install instead of npm ci
[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "node src/app.js"
healthcheckPath = "/health"
healthcheckTimeout = 100

[nixpacks]
install_cmd = "npm install"  # Explicitly specify npm install instead of npm ci
nodejs-version = "18"