# railway.toml - Updated for Socket Mode
[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "node src/app.js"
healthcheckPath = "/health"
healthcheckTimeout = 100

[nixpacks]
install_cmd = "npm install"
nodejs-version = "18"